name: Push latest
on:
  push:
    branches:
      - develop
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/bootstrapping_tools:latest --tag islasgeci/bootstrapping_tools:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci/bootstrapping_tools:latest make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci/bootstrapping_tools:latest make coverage
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/bootstrapping_tools:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/bootstrapping_tools:${GITHUB_SHA:0:4}
  mutants:
    - name: Evalúa resistencia a mutaciones
      run: docker run islasgeci/bootstrapping_tools:latest make mutants
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        skip_existing: true